name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: write

jobs:
  setup-environment:
    name: Set env vars
    runs-on: ubuntu-latest
    outputs:
      cargo_cache_key: ${{ steps.cargo_cache_key.outputs.value }}
    steps:
      - uses: actions/checkout@v4
      - name: Set cargo cache key
        id: cargo_cache_key
        run: |
          CARGO_CACHE_KEY="${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}"
          echo "value=$CARGO_CACHE_KEY" >> $GITHUB_ENV
          echo "::set-output name=value::$CARGO_CACHE_KEY"

  lint:
    needs: setup-environment
    uses: ./.github/workflows/lint.yml
    with:
      cache-key: ${{ needs.setup-environment.outputs.cargo_cache_key }}

  test:
    name: Test
    needs: setup-environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            ~/.cargo/bin
          key: ${{ needs.setup-environment.outputs.cargo_cache_key }}
          id: cache-cargo-test

      - name: Cargo test
        run: cargo test --release --workspace --all-targets --all-features

  check-msrv:
    uses: ./.github/workflows/msrv.yml
